name: system_settings
description: Flutter plugin to open system and app settings on iOS and Android.
version: 3.0.1
homepage: https://onepub.dev/packages/system_settings/znnooflygz
repository: https://onepub.dev/packages/system_settings/znnooflygz

environment:
  sdk: '>=2.15.1 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.florianweinaug.system_settings
        pluginClass: SystemSettingsPlugin
      ios:
        pluginClass: SystemSettingsPlugin
publish_to: https://onepub.dev/api/znnooflygz/
